Update testing.yml

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -11,9 +11,19 @@ jobs:
         a: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
         b: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
       max-parallel: 1
-      
+
     steps:
-      # Step 3: Install cloudflared
+      - name: Restore database from Releases (if exists)
+        run: |
+          mkdir -p $HOME/.kspanel
+          if gh release view latest-db >/dev/null 2>&1; then
+            echo "Release found. Downloading database..."
+            gh release download latest-db -p "database.zip" -D /tmp
+            unzip -o /tmp/database.zip -d $HOME/.kspanel
+          else
+            echo "No previous database release found."
+          fi
+
       - name: Download and install cloudflared
         run: |
           echo "Downloading cloudflared..."
@@ -21,11 +31,10 @@ jobs:
           chmod +x cloudflared
           sudo mv cloudflared /usr/local/bin/
 
-      # Step 4: Install cloudflared service with your token
       - name: Install cloudflared service
         run: |
           sudo cloudflared service install eyJhIjoiZTJkZjY3MDI5ZWZlZTBmY2JhM2ExMjNjN2VmNTcxNTAiLCJ0IjoiMGQ2Yzk5YjQtMGUzZC00NzEyLWFmNDctNzM0MGU5YTEyOGE3IiwicyI6IlkyVTNOelV5WmpBdFl6SmpOeTAwTjJZMExUbGpNMk10T0dJelltRmtOREk1T1dOaCJ9
-          
+
       - name: Prepare KS Panel
         run: |
           wget https://raw.githubusercontent.com/ks-app-518/ksanel-testing/refs/heads/main/kspanel
@@ -37,19 +46,18 @@ jobs:
           kspanel database
           kspanel install
           kspanel start
-          
-      - name: Install tmate from URL
+
+      - name: Install tmate
         run: |
           curl -L https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz -o tmate.tar.xz
           tar -xf tmate.tar.xz
           chmod +x tmate-2.4.0-static-linux-amd64/tmate
           sudo mv tmate-2.4.0-static-linux-amd64/tmate /usr/bin/tmate
           tmate -V
-    
+
       - name: Start vps-runtime
         run: |
           TMATE_SOCK=/tmp/tmate.sock
-
           tmate -S $TMATE_SOCK new-session -d
           tmate -S $TMATE_SOCK wait tmate-ready
 
@@ -59,4 +67,20 @@ jobs:
           echo "Web connection:"
           tmate -S $TMATE_SOCK display -p "#{tmate_web}"
 
-          sleep 21300 
+          sleep 21300
+
+      - name: Zip database
+        run: |
+          if [ -d "$HOME/.kspanel/database" ]; then
+            cd $HOME/.kspanel
+            zip -r database.zip database
+            mv database.zip /tmp/database.zip
+          else
+            echo "Database folder not found"
+            exit 0
+          fi
+
+      - name: Upload database to Releases
+        run: |
+          gh release delete latest-db -y || true
+          gh release create latest-db /tmp/database.zip -t "Latest Database" -n "Auto saved KS Panel database"
